version: '2'
services:
    web:
        image: didyoun/ubuntu-nginx
        ports:
            - "8080:80"
        volumes:
            - .:/data/www/

            - ./utils/docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
            - ./utils/docker/nginx/conf/conf.d/default.conf:/etc/nginx/conf.d/default.conf

            - ./utils/docker/nginx/log/error.log:/var/log/nginx/error.log
            - ./utils/docker/nginx/log/access.log:/var/log/nginx/access.log
        links:
            - phpfpm:phpfpm
            - mysql:db
        environment:
            MYSQL_DB_LOGIN : root
            MYSQL_DB_PASSWORD : admin
            MYSQL_DB_HOST : db
    phpfpm:
        image: didyoun/php7-fpm
        ports:
            - "9000:9000"
        volumes:
            - .:/data/www/
    mysql:
        image: mysql
        environment:
            MYSQL_DATABASE: app
            MYSQL_ROOT_PASSWORD: admin
        ports:
            - "3306:3306"
        volumes:
            - ./utils/docker/mysql:/var/lib/mysql
            - ./utils/docker/data/:/data/import/
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql:db
        ports:
            - "8183:80"
        environment:
            PMA_USER: root
            PMA_PASSWORD: admin
            PMA_ARBITRARY: 1
