version: '2'
services:
    web:
        image: didyoun/ubuntu-nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        links:
            - phpfpm:phpfpm
            - mysql:db
        environment:
            MYSQL_DB_LOGIN : root
            MYSQL_DB_PASSWORD : admin
            MYSQL_DB_HOST : db
    phpfpm:
        image: zendpokemon_phpfpm
        ports:
            - "9000:9000"
        volumes:
            - .:/data/www/
    mysql:
        image: mysql
        environment:
            MYSQL_DATABASE: app
            MYSQL_ROOT_PASSWORD: admin
        ports:
            - "3306:3306"
        volumes:
            - ./utils/docker/mysql:/var/lib/mysql
            - ./utils/docker/data/:/data/import/
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql:db
        ports:
            - "8183:80"
        environment:
            PMA_USER: root
            PMA_PASSWORD: admin
            PMA_ARBITRARY: 1
